version: '3'
services:

  verdaccio:
    image: verdaccio/verdaccio:5.30.3
    container_name: verdaccio
    hostname: verdaccio
    volumes:
      - "/opt/verdaccio/conf:/verdaccio/conf"
      - "/opt/verdaccio/storage:/verdaccio/storage"
    restart: always

  nexus3:
    image: sonatype/nexus3:3.68.1
    container_name: nexus3
    hostname: nexus3
    volumes:
      - "/data/nexus-data:/nexus-data"
    environment:
      INSTALL4J_ADD_VM_PARAMS: "-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data/javaprefs"
    restart: always
  
  nginx:
    image: nginx:1.24-alpine
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./conf/nginx:/etc/nginx/conf.d"
      - "./conf/cert:/etc/nginx/ssl"
    restart: always
    depends_on:
      - verdaccio
      - nexus3
