services:

  samba-test:
    image: registry.inventec/development/samba-test:latest
    container_name: samba-test
    hostname: samba-test
    ports:
      - "8080:8080"
    # volumes:
    #   - /data/vscode:/home/root/.vscode
    restart: always
    # cpu_count: 2
    # mem_limit: 4g
    networks:
      - net

networks:
  net:
    external: true
    name: infra
