services:

  samba:
    image: dperson/samba:latest
    container_name: samba
    hostname: samba
    ports:
      - "445:445/tcp"
      - "139:139/tcp" 
    volumes:
      - ./volume/res:/share:rw 
    environment:
      TZ: 'Asia/Shanghai'
    command: '-s "public;/share;yes;no;no;dev" -u "dev;111111" -S'
    restart: always
    cpu_count: 2
    mem_limit: 4g
    networks:
      - net

networks:
  net:
    external: true
    name: infra

# Ref: https://github.com/miketeo/pysmb/issues/95#issuecomment-535349556
# command: '-s "public;/share;yes;no;no;dev" -u "dev;111111" -g "server min protocol = LANMAN1"'
