FROM openjdk:jre-alpine
LABEL maintainer="Zhang.Xing-Long@inventec.com"
ARG JAR_FILE

COPY ${JAR_FILE} /opt/app.jar

WORKDIR /opt
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/opt/app.jar"]
