global:
  # How frequently to scrape targets by default.
  scrape_interval: 15s
  # 评估 规则文件中配置的各个报警表达式 的时间间隔，默认为15s
  evaluation_interval: 60s

rule_files:
  # - "jvm-alert-rules.yml"
  - "common-alert-rules.yml"
  # - "mongo-alert-rules.yml"
  - "flink-alert-rules.yml"
  - "postgres-alert-rules.yml"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'kafka'
    scrape_interval: 60s
    scrape_timeout: 20s
    static_configs:
    - targets: 
      - 10.191.5.218:9990

  # - job_name: 'redis'
  #   static_configs:
  #   - targets:
  #     - redis://10.191.7.1:7505
  #     - redis://10.191.7.1:7506
  #     - redis://10.191.7.2:7501
  #     - redis://10.191.7.2:7502
  #     - redis://10.191.7.3:7503
  #     - redis://10.191.7.3:7504
  #   metrics_path: /scrape
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: redis-exporter:9121

  - job_name: 'host'
    scrape_interval: 30s
    scrape_timeout: 30s
    static_configs:
    - targets: 
      - 10.191.5.218:9100

  - job_name: 'postgres'
    scrape_interval: 30s
    scrape_timeout: 30s
    static_configs:
    - targets: 
      - postgres-exporter:9187

  - job_name: 'greenplum'
    scrape_interval: 60s
    scrape_timeout: 60s
    static_configs:
    - targets: 
      - greenplum-exporter:9187

  # - job_name: 'prometheus'
  #   static_configs:
  #   - targets: ['127.0.0.1:9090']

  # - job_name: 'ceph'
  #   static_configs:
  #   - targets: ['10.191.5.218:9283']

  - job_name: 'dcagent'
    scrape_interval: 30s
    static_configs:
    # SPI 小图
    - labels: { line: "S08", side: "A", station: "SPI", area: "PCA"}
      targets: ["10.191.5.218:12345"]

  # - job_name: 'elasticsearch'
  #   static_configs:
  #   - targets: ['elasticsearch-exporter:9114']

  # - job_name: 'mongodb'
  #   static_configs:
  #   - targets: ['mongodb-exporter:9216']

  # - job_name: 'mysqld'
  #   static_configs:
  #   - targets: ['mysqld-exporter:9104']

  # - job_name: 'nginx'
  #   static_configs:
  #   - targets: ['nginx-exporter:9104']

  # - job_name: 'rabbitmq'
  #   static_configs:
  #   - targets: ['rabbitmq-exporter:9104']

  # - job_name: 'minio'
  #   # bearer_token: <secret>
  #   metrics_path: /minio/v2/metrics/cluster
  #   scheme: http
  #   static_configs:
  #   - targets: 
  #     - 

  # - job_name: 'mssql'
  #   scrape_interval: 30s
  #   scrape_timeout: 30s
  #   static_configs:
  #   - targets: 
  #     - mssql-exporter:9273

  - job_name: 'kafka-connect'
    scrape_interval: 120s
    scrape_timeout: 60s
    static_configs:
    - targets: 
      - 10.191.5.218:9991

  - job_name: 'kafka-lag'
    scrape_interval: 60s
    scrape_timeout: 30s
    static_configs:
    - targets: 
      - kafka-lag-exporter:8000
    metric_relabel_configs:
      - regex: 'consumer_id'
        action: labeldrop

