# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH

source /usr/local/greenplum-db/greenplum_path.sh
export MASTER_DATA_DIRECTORY=/disk1/gpdata/gpmaster/gpseg-1
export PGPORT=5432
export PGDATABASE=ictlog
source /usr/local/greenplum-cc-web/gpcc_path.sh
