FROM registry.inventec/proxy/library/alpine:latest
LABEL maintainer="Zhang.Xing-Long@inventec.com"

RUN apk update && \
    # 新版 docker-cli 需要额外安装 docker-cli-buildx
    apk add --no-cache make docker-cli docker-cli-buildx git curl && \
    # 支持 CD 至 Minio
    # https://docs.min.io/docs/minio-client-quickstart-guide.html
    curl https://dl.min.io/client/mc/release/linux-amd64/mc -o /usr/local/bin/mc && \
    chmod +x /usr/local/bin/mc && \
    # 支持 CD 至 K8S
    # https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/ 
    curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o /usr/local/bin/kubectl && \
    chmod +x /usr/local/bin/kubectl
