version: "2.3"
services:
  
  gp6mdw:
    image: ${REGISTRY}/${TAGNAME}
    container_name: gp6mdw
    hostname: gp6mdw
    ports:
      - 5483:5432
    volumes:
      - /opt/bdcc/greenplum6/config:/opt/greenplum/config
      - /data/ssd2/gp6data:/disk1/gpdata
    environment:
      MIRROR_STRATEGY: Spread
      IS_MASTER: "true"
      # ENABLE_RESOURCE_GROUPS: "true"
    restart: always
    # privileged: true
    # cpu_count: 28
    # mem_limit: 160g
    sysctls:
      - net.ipv4.ipfrag_time=60
      - net.ipv4.ipfrag_high_thresh=12480000
      # 以下几项需要在宿主机上修改，不支持容器单独配置 
      # sysctl 'vm.dirty_background_bytes=1610612736' is not whitelisted
      # - vm.overcommit_memory=2
      # - vm.overcommit_ratio=80
      # - vm.dirty_ratio=0
      # - vm.dirty_bytes=4294967296
      # - vm.dirty_background_ratio=0
      # - vm.dirty_background_bytes=1610612736
    cap_add:
      - SYS_PTRACE

networks:
  default:
    external: true
    name: bdc
