version: '2.3'
services:

  mongo:
    image: mongo:4.0.14
    container_name: mongo
    hostname: mongo
    # network_mode: host
    ports:
      - "27017:27017"
    volumes:
      - /data/ssd1/mongo/configdb:/data/configdb
      - /data/ssd1/mongo/db:/data/db
      - /data/ssd1/mongo/logs:/data/logs
      - /etc/localtime:/etc/localtime:ro
      - ./setup:/docker-entrypoint-initdb.d
    command: --port 27017 --dbpath /data/db --logpath /data/logs/mongod.log --logappend --auth
    restart: always
    cpu_count: 2
    mem_limit: 4g
