services:
  seatunnel:
    image: registry.inventec/infra/seatunnel:2.3.9
    container_name: seatunnel
    volumes:
      - ./examples:/opt/tasks
    environment:
      FLINK_REST_ADDRESS: 10.191.7.13
      FLINK_REST_PORT: 30651
    command: tail -f /dev/null
    restart: always

networks:
  default:
    external: true
    name: infra
