#
# This is the config file used for the docker images.
# It allows all users to do anything, so don't use it on production systems.
#
# Do not configure host and port under `listen` in this file
# as it will be ignored when using docker.
# see https://verdaccio.org/docs/en/docker#docker-and-custom-port-configuration
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /verdaccio/storage
# path to a directory with plugins to include
plugins: /verdaccio/plugins

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  enable: true
  title: ITC NPM Private Repo
  primary_color: "#cd0806"

auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
    # Maximum amount of users allowed to register, defaults to "+infinity".
    # You can set this to -1 to disable registration.
    # max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    maxage: 1d
    max_fails: 2
    timeout: 120s

  cnpmjs:
    url: https://registry.npmmirror.com/
    maxage: 1d
    max_fails: 2
    timeout: 60s

  yarnpkg:
    url: https://registry.yarnpkg.com/
    maxage: 1d
    max_fails: 2
    timeout: 120s

packages:
  '@itc-*/*':
    access: $all
    publish: $authenticated

  'e-planet-*':
    # scoped packages
    access: $all
    publish: $authenticated

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true

# log settings
logs:
  - {type: stdout, format: pretty, level: trace}
  # - {type: file, path: verdaccio.log, level: info}

# Proxies are special-purpose HTTP servers designed to transfer data from remote servers to local clients.
# http_proxy: 
# https_proxy: 
# no_proxy: localhost,127.0.0.1

max_body_size: 50mb
