version: '2.3'
services:

  jenkins:
    image: registry.inventec/infra/jenkins:2.204.1-centos
    container_name: jenkins
    network_mode: host
    # ports:
    #   - 8080:8080
    #   - 50000:50000
    volumes:
      - ./data/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/bin/docker
    group_add:
      - ${DOCKER_GID}
    restart: always
    cpu_count: 2
    mem_limit: 4g

# DOCKER_GID=$(stat -c '%g' /var/run/docker.sock)
# echo "DOCKER_GID=${DOCKER_GID}" > .env
