{
 "title": "Greenplum",
 "description": "Greenplum集群监控状态图",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Zone", "query": "prometheus" },
   { "name": "instance", "query": { "query": "label_values(gp_up,  server)" } }
  ]
 },
 "panels": [
  { "title": "Service Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gp_up{server=\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gp_stat_activity_count{server=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Down Segment",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gp_segment_up{server=\"$instance\"}==0)"
    }
   ]
  },
  {
   "title": "Not Prefered Segs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gp_segment_role_change{server=\"$instance\"}==1)"
    }
   ]
  },
  {
   "title": "Standby State",
   "type": "stat",
   "description": "gpstate -f",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gp_segment_up{server=\"$instance\", content=\"-1\", preferred_role=\"m\"}==1)"
    }
   ]
  },
  {
   "title": "Statement Timeout",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gp_settings_param{server=\"$instance\", name=\"statement_timeout\"}"
    }
   ]
  },
  {
   "title": "Lock Timeout",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gp_settings_param{server=\"$instance\", name=\"lock_timeout\"}"
    }
   ]
  },
  {
   "title": "Inter Transmit Timeout",
   "type": "stat",
   "description": "防止 UDP 丢包造成 SQL 执行阻塞",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gp_settings_param{server=\"$instance\", name=\"gp_interconnect_transmit_timeout\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - gp_postmaster_start_time_seconds{server=\"$instance\"}",
     "legendFormat": "运行时间"
    }
   ]
  },
  {
   "title": "Vmem Protect Limit",
   "type": "stat",
   "description": "Segment ",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gp_settings_param{server=\"$instance\", name=\"gp_vmem_protect_limit\"}"
    }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "description": "Segment ",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gp_settings_param{server=\"$instance\", name=\"shared_buffers\"}*32"
    }
   ]
  },
  {
   "title": "Maintenace Memory",
   "type": "stat",
   "description": "Segment",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gp_settings_param{server=\"$instance\", name=\"maintenance_work_mem\"}"
    }
   ]
  },
  {
   "title": "Statement Memory",
   "type": "stat",
   "description": "Segment ",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gp_settings_param{server=\"$instance\", name=\"statement_mem\"}"
    }
   ]
  },
  {
   "title": "Temp Buffers",
   "type": "stat",
   "description": "Segment ",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gp_settings_param{server=\"$instance\", name=\"temp_buffers\"}*32"
    }
   ]
  },
  {
   "title": "Interconnect Queue Depth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gp_settings_param{server=\"$instance\", name=\"gp_interconnect_queue_depth\"}"
    }
   ]
  },
  { "title": "Running State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Client Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (application_name, client_addr, datname, state) (gp_stat_activity_count{server=\"$instance\"})",
     "legendFormat": "{{datname}}-{{application_name}}-{{client_addr}}-{{state}}"
    },
    {
     "expr": "gp_settings_param{name=\"max_connections\", server=\"$instance\"}",
     "legendFormat": "max_connections"
    },
    {
     "expr": "sum(gp_stat_activity_count{server=\"$instance\"})",
     "legendFormat": "total_connections"
    }
   ]
  },
  {
   "title": "TPS && Lock",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (application_name, datname) (gp_stat_activity_count{server=\"$instance\", state=\"active\", waiting=\"true\"})",
     "legendFormat": "{{datname}}-{{application_name}}-lock"
    },
    {
     "expr": "sum(gp_stat_activity_count{server=\"$instance\", state=\"active\"})",
     "legendFormat": "TPS"
    },
    {
     "expr": "sum(gp_stat_activity_count{server=\"$instance\", state=\"active\", waiting=\"true\"})",
     "legendFormat": "lock"
    }
   ]
  },
  {
   "title": "Transcation Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (application_name, datname) (gp_stat_activity_active_max_tx_duration{server=\"$instance\"})",
     "legendFormat": "{{datname}}-{{application_name}}"
    }
   ]
  },
  {
   "title": "Resource Queue Memory ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gp_resqueue_status_rsqmemoryvalue{server=\"$instance\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Fault Segment",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "gp_segment_role_change{server=\"$instance\", preferred_role=\"m\"}>0",
     "legendFormat": "{{hostname}}-{{content}}-{{preferred_role}}"
    },
    {
     "expr": "gp_segment_up{server=\"$instance\"}==0",
     "legendFormat": "{{hostname}}-{{content}}-{{preferred_role}}"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gp_database_size_bytes{server=\"$instance\"} * 1.1",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Growth of database",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(gp_database_size_bytes{server=\"$instance\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Spill Files",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (hostname) (gp_workfile_size{server=\"$instance\", hostname!=\"\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Pending SQL",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gp_locks_waiting_duration_seconds{server=\"$instance\", lock=\"AccessExclusiveLock\"}"
    },
    {
     "expr": "gp_locks_waiting_duration_seconds{server=\"$instance\", waiting_lock=\"AccessExclusiveLock\"}"
    }
   ]
  }
 ]
}