{
 "title": "Kafka Cluster",
 "description": "Dashboard for metrics jmx_exporter protmetheus",
 "tags": [ "kafka" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Zone", "query": "prometheus" },
   {
    "name": "job",
    "label": "Cluster",
    "query": {
     "query": "label_values(kafka_controller_kafkacontroller_controllerstate, job)"
    }
   },
   {
    "name": "broker",
    "label": "Broker",
    "query": {
     "query": "label_values(kafka_controller_kafkacontroller_controllerstate{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_server_brokertopicmetrics_bytesout_total{job=\"$job\"}, topic)"
    }
   },
   {
    "name": "online_broker",
    "query": {
     "query": "query_result(count(up{job=~\"$job\"}))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$broker Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "repeat": "broker",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$broker Restarts in selected time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "repeat": "broker",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changes(process_start_time_seconds{job=\"$job\",instance=~\"$broker\"}[$__range])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Cluster health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Online Brokers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_controller_kafkacontroller_activecontrollercount{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Total of Topics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "ISR Shinks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kafka_server_replicamanager_isrshrinks_total{job=\"$job\"}[5m])) + sum(increase(kafka_server_replicamanager_isrexpands_total{job=\"$job\"}[5m]))"
    }
   ]
  },
  {
   "title": "ZooKeeperExpires",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(kafka_server_sessionexpirelistener_zookeeperexpires{job=\"$job\"}[$__range])))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(sum(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"$job\"}[5m])), 0.1)",
     "legendFormat": "MessagesIn/s"
    }
   ]
  },
  {
   "title": "Non-HA Topics",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(sum(kafka_cluster_partition_replicascount{job=~\"$job\"})by(topic, partition) == 1)by(topic))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitions per Broker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sort(sum(kafka_server_replicamanager_partitioncount{job=\"$job\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Partitions Leader and Replica Per Broker",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 13 },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_leadercount{job=\"$job\"} / kafka_server_replicamanager_partitioncount{job=\"$job\"} * 100"
    },
    {
     "expr": "kafka_server_replicamanager_leadercount{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate\n(kafka_network_requestmetrics_requests_total{job=\"$job\",instance=~\"$broker\"}[5m])) by (instance, request) >1",
     "legendFormat": "{{instance}}-{{request}}"
    },
    {
     "expr": "increase\n(kafka_server_sessionexpirelistener_zookeeperexpires{job=\"$job\",instance=~\"$broker\"}[5m])",
     "legendFormat": "{{instance}}-zookeeperexpires"
    }
   ]
  },
  {
   "title": "Errors Per 5m ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_network_requestmetrics_errors_total{job=\"$job\",instance=~\"$broker\", error!=\"NONE\"}[5m])) by (instance, request, error) > 0",
     "legendFormat": "{{instance}}-{{request}}-{{error}}"
    }
   ]
  },
  {
   "title": "NetworkProcessorAvgIdlePercent",
   "type": "stat",
   "description": "NetworkProcessorAvgIdlePercent",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_network_socketserver_networkprocessoravgidlepercent{job=\"$job\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RequestHandlerAvgIdlePercent",
   "type": "stat",
   "description": "RequestHandlerAvgIdlePercent",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent{job=\"$job\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Produce Latency (99th) per Broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_totaltimems{request=\"Produce\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-total"
    },
    {
     "expr": "kafka_network_requestmetrics_remotetimems{request=\"Produce\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-remote"
    },
    {
     "expr": "kafka_network_requestmetrics_responsequeuetimems{request=\"Produce\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-responsequeue"
    },
    {
     "expr": "kafka_network_requestmetrics_responsesendtimems{request=\"Produce\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-responsesend"
    },
    {
     "expr": "kafka_network_requestmetrics_localtimems{request=\"Produce\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-local"
    },
    {
     "expr": "kafka_network_requestmetrics_totaltimems{request=\"Produce\",job=\"$job\",quantile=\"0.95\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-total95"
    },
    {
     "expr": "kafka_network_requestmetrics_requestqueuetimems{request=\"Produce\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-requestqueue"
    },
    {
     "expr": "kafka_network_requestmetrics_throttletimems{request=\"Produce\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-throttletimems"
    }
   ]
  },
  {
   "title": "FetchFollower Latency (99th) per Broker",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_totaltimems{request=\"FetchFollower\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-total"
    },
    {
     "expr": "kafka_network_requestmetrics_remotetimems{request=\"FetchFollower\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-remote"
    },
    {
     "expr": "kafka_network_requestmetrics_responsequeuetimems{request=\"FetchFollower\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-responsequeue"
    },
    {
     "expr": "kafka_network_requestmetrics_responsesendtimems{request=\"FetchFollower\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-responsesend"
    },
    {
     "expr": "kafka_network_requestmetrics_localtimems{request=\"FetchFollower\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-local"
    },
    {
     "expr": "kafka_network_requestmetrics_totaltimems{request=\"FetchFollower\",job=\"$job\",quantile=\"0.95\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-total95"
    }
   ]
  },
  {
   "title": "FetchConsumer Latency (99th) per Broker",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_totaltimems{request=\"FetchConsumer\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-total"
    },
    {
     "expr": "kafka_network_requestmetrics_remotetimems{request=\"FetchConsumer\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-remote"
    },
    {
     "expr": "kafka_network_requestmetrics_responsequeuetimems{request=\"FetchConsumer\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-responsequeue"
    },
    {
     "expr": "kafka_network_requestmetrics_responsesendtimems{request=\"FetchConsumer\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-responsesend"
    },
    {
     "expr": "kafka_network_requestmetrics_localtimems{request=\"FetchConsumer\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-local"
    },
    {
     "expr": "kafka_network_requestmetrics_totaltimems{request=\"FetchConsumer\",job=\"$job\",quantile=\"0.95\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-total95"
    }
   ]
  },
  {
   "title": "OffsetCommit Latency (99th) per Broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_totaltimems{request=\"OffsetCommit\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-total"
    },
    {
     "expr": "kafka_network_requestmetrics_remotetimems{request=\"OffsetCommit\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-remote"
    },
    {
     "expr": "kafka_network_requestmetrics_responsequeuetimems{request=\"OffsetCommit\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-responsequeue"
    },
    {
     "expr": "kafka_network_requestmetrics_responsesendtimems{request=\"OffsetCommit\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-responsesend"
    },
    {
     "expr": "kafka_network_requestmetrics_localtimems{request=\"OffsetCommit\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-local"
    },
    {
     "expr": "kafka_network_requestmetrics_totaltimems{request=\"OffsetCommit\",job=\"$job\",quantile=\"0.95\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-total95"
    },
    {
     "expr": "kafka_network_requestmetrics_throttletimems{request=\"OffsetCommit\",job=\"$job\",quantile=\"0.95\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-throttletimems"
    }
   ]
  },
  {
   "title": "Fetch Purgatory Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_delayedoperationpurgatory_purgatorysize_fetch{job=\"$job\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ApiVersions Latency (99th) per Broker",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_totaltimems{request=\"ApiVersions\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-total"
    },
    {
     "expr": "kafka_network_requestmetrics_remotetimems{request=\"ApiVersions\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-remote"
    },
    {
     "expr": "kafka_network_requestmetrics_responsequeuetimems{request=\"ApiVersions\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-responsequeue"
    },
    {
     "expr": "kafka_network_requestmetrics_responsesendtimems{request=\"ApiVersions\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-responsesend"
    },
    {
     "expr": "kafka_network_requestmetrics_totaltimems{request=\"ApiVersions\",job=\"$job\",quantile=\"0.95\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}-total95"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Bytes In / Out Per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "Bps", "label": "In (-) / Out (+)" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesout_total{job=\"$job\",instance=~\"$broker\"}[5m]))by(instance)",
     "legendFormat": "Bytes Out [{{instance}}]"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesin_total{job=\"$job\",instance=~\"$broker\"}[5m]))by(instance)",
     "legendFormat": "Bytes In [{{instance}}]"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic TOPN",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(10, sum(irate(kafka_server_brokertopicmetrics_bytesin_total{job=\"$job\",instance=~\"$broker\",topic=~\"$topic\"}[5m]))by(topic)\n)",
     "legendFormat": "Bytes In [{{topic}}]"
    },
    {
     "expr": "topk(20, sum(irate(kafka_server_brokertopicmetrics_messagesin_total{job=\"$job\",instance=~\"$broker\",topic=~\"$topic\"}[5m]))by(topic)\n)",
     "legendFormat": "Message In [{{topic}}]"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic TOPN",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(\n10,\nsum(irate(kafka_server_brokertopicmetrics_bytesout_total{job=\"$job\",topic!=\"\",instance=~\"$broker\",topic=~\"$topic\"}[5m]))by(topic)\n)",
     "legendFormat": "Bytes Out [{{topic}}]"
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "ConsumerGroup Lag",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum without(client_id, member_host, partition)(kafka_consumergroup_group_lag{cluster_name=\"$job\", topic=~\"$topic\"})",
       "legendFormat": "{{topic}}-{{group}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rest Proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Latency Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_rest_jersey_metrics_topic_produce_json_v2_request_latency_max{job=\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_rest_jersey_metrics_topic_produce_json_v2_request_rate{job=\"$job\"}",
       "legendFormat": "{{instance}}-request"
      },
      {
       "expr": "kafka_rest_jersey_metrics_topic_produce_json_v2_request_error_rate{job=\"$job\"}",
       "legendFormat": "{{instance}}-error"
      }
     ]
    }
   ]
  },
  { "title": "LogCleaner", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Recopy Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "kafka_log_logcleaner_cleaner_recopy_percent{job=~\"$job\", instance=~\"$broker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Clean Time (最后一次)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kafka_log_logcleaner_max_clean_time_secs{job=~\"$job\", instance=~\"$broker\"}>0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Topics (1 Replicas)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "Non-HA Topics",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "count(sum(kafka_cluster_partition_replicascount{job=~\"$job\", topic=~\"$topic\"})by(topic, partition) == 1)by(topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  }
 ]
}