{
 "title": "MinIO Overview",
 "description": "MinIO dashboard - https://min.io/",
 "tags": [ "minio" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Zone", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Domain",
    "query": {
     "query": "label_values(minio_software_version_info,instance)"
    }
   },
   {
    "name": "disk",
    "label": "Drive",
    "query": {
     "query": "label_values(minio_node_disk_total_bytes{instance=~\"$instance\"},disk)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "S3 API Request & Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(minio_s3_requests_total{instance=~\"$instance\"}[5m])) by(api)>0",
     "legendFormat": "S3 Requests-{{api}}"
    },
    {
     "expr": "sum(rate(minio_s3_requests_errors_total{instance=~\"$instance\"}[5m])) by(api)>0",
     "legendFormat": "S3 Errors-{{api}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "rate(minio_node_go_routine_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Data Growth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(minio_bucket_usage_total_bytes{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "Total Storage Used"
    },
    {
     "expr": "sum(minio_cluster_usage_total_bytes{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "Total Storage Used"
    }
   ]
  },
  {
   "title": "S3 API Data Transfer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(minio_s3_traffic_sent_bytes{instance=~\"$instance\"}[5m]))",
     "legendFormat": "S3 Data Sent"
    },
    {
     "expr": "sum(rate(minio_s3_traffic_received_bytes{instance=~\"$instance\"}[5m]))",
     "legendFormat": "S3 Data Received"
    }
   ]
  },
  {
   "title": "minio_notify_target_queue_length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "minio_notify_target_queue_length{instance=~\"$instance\"}",
     "legendFormat": "{{server}}-{{target_name}}"
    }
   ]
  },
  {
   "title": "Object size distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (range) (minio_bucket_objects_size_distribution{instance=~\"$instance\"})",
     "legendFormat": "{{range}}"
    },
    {
     "expr": "sum by (range) (minio_cluster_objects_size_distribution{instance=~\"$instance\"})",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Offline Disk",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "minio_cluster_disk_offline_total{instance=~\"$instance\"}>0",
     "legendFormat": "{{server}}"
    }
   ]
  }
 ]
}