{
 "title": "PostgreSQL Cluster",
 "description": "Dashboard for PostgreSQL Statistics.",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(pg_static, server)"
    }
   },
   {
    "name": "db",
    "label": "Database",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{datname!~\"template.*|postgres|.*_del|.*_bak\", server=\"$instance\"},datname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Settings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_static{server=\"$instance\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{server=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{server=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_wal_size_bytes{server=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Checkpoint Completion Target",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_checkpoint_completion_target{server=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Statement Timeout",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_statement_timeout_seconds{server=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Lock Timeout",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_lock_timeout_seconds{server=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_worker_processes{server=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - pg_postmaster_start_time_seconds{server=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_maintenance_work_mem_bytes{server=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Temp Buffers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_temp_buffers_bytes{server=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Checkpoint Timeout",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_checkpoint_timeout_seconds{server=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes{server=\"$instance\"}"
    }
   ]
  },
  {
   "title": "idle_in_transaction Timeout",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_idle_in_transaction_session_timeout_seconds{server=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Autovacuum Max Workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_autovacuum_max_workers{server=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max Parallel Workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_parallel_workers{server=\"$instance\"}"
    }
   ]
  },
  { "title": "Running State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{server=\"$instance\", datname=~\"$db\"}",
     "legendFormat": "{{datname}}-{{state}}"
    },
    {
     "expr": "pg_settings_max_connections{server=\"$instance\"}",
     "legendFormat": "max_connections"
    },
    {
     "expr": "sum(pg_stat_activity_count{server=\"$instance\", datname=~\"$db\"})",
     "legendFormat": "total_connections"
    }
   ]
  },
  {
   "title": "Idle Connections TOP40",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(40, pg_stat_activity_idle_count{server=\"$instance\", datname=~\"$db\"})>0",
     "legendFormat": "{{usename}}-{{client_addr}}-{{application_name}}"
    }
   ]
  },
  {
   "title": "TPS && Rollbak",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{server=\"$instance\", datname=~\"$db\"}[5m])",
     "legendFormat": "{{datname}}-commits"
    },
    {
     "expr": "rate(pg_stat_database_xact_rollback{server=\"$instance\", datname=~\"$db\"}[5m])>0",
     "legendFormat": "{{datname}}-rollbacks"
    }
   ]
  },
  {
   "title": "Longest Transaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration{server=\"$instance\", datname=~\"$db\"}",
     "legendFormat": "{{datname}}-max_tx_duration [{{state}}]"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{server=\"$instance\", datname=~\"$db\"}",
     "legendFormat": "{{datname}}"
    },
    {
     "expr": "predict_linear(pg_database_size_bytes{server=\"$instance\", datname=~\"$db\"}[7d], 24*3600) ",
     "legendFormat": "{{datname}}-predict"
    },
    {
     "expr": "sum by(server) (pg_database_size_bytes{server=\"$instance\", datname=~\"$db\"})",
     "legendFormat": "total_size"
    }
   ]
  },
  {
   "title": "Wal Incr && Replay Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_stat_replication_pg_wal_lsn_diff{server=\"$instance\", state!=\"catchup\"}",
     "legendFormat": "{{server}}-wal-lag-{{application_name}}"
    },
    {
     "expr": "max(rate(pg_stat_replication_pg_current_wal_lsn_bytes{server=\"$instance\"}[5m]))by(server)",
     "legendFormat": "{{server}}-wal-incr"
    }
   ]
  },
  {
   "title": "Buffers (bgwriter)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend{server=\"$instance\"}[5m])",
     "legendFormat": "buffers_backend"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_alloc{server=\"$instance\"}[5m])",
     "legendFormat": "buffers_alloc"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_checkpoint{server=\"$instance\"}[5m])",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_clean{server=\"$instance\"}[5m])",
     "legendFormat": "buffers_clean"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_hit{server=\"$instance\", datname=~\"$db\"}[5m]) / \n(rate(pg_stat_database_blks_read{server=\"$instance\", datname=~\"$db\"}[5m]) + rate(pg_stat_database_blks_hit{server=\"$instance\", datname=~\"$db\"}[5m]))",
     "legendFormat": "{{datname}}-Cache Hit Rate"
    }
   ]
  },
  {
   "title": "Read Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_fetched{server=\"$instance\", datname=~\"$db\"}[5m])",
     "legendFormat": "{{datname}}-SELECT (index scan)"
    },
    {
     "expr": "irate(pg_stat_database_tup_returned{server=\"$instance\", datname=~\"$db\"}[5m])",
     "legendFormat": "{{datname}}-SELECT (table scan)"
    }
   ]
  },
  {
   "title": "Change Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Rows" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_inserted{server=\"$instance\", datname=~\"$db\"}[5m])",
     "legendFormat": "{{datname}}-INSERT"
    },
    {
     "expr": "irate(pg_stat_database_tup_updated{server=\"$instance\", datname=~\"$db\"}[5m])",
     "legendFormat": "{{datname}}-UPDATE"
    },
    {
     "expr": "irate(pg_stat_database_tup_deleted{server=\"$instance\", datname=~\"$db\"}[5m])",
     "legendFormat": "{{datname}}-DELETE"
    }
   ]
  },
  {
   "title": "Temp File Size",
   "type": "graph",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_temp_bytes{server=\"$instance\", datname=~\"$db\"}[5m])",
     "legendFormat": "{{datname}}-Temp Bytes"
    }
   ]
  },
  {
   "title": "blk_w/r_time /s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blk_write_time{server=\"$instance\", datname=~\"$db\"}[5m])",
     "legendFormat": "{{datname}}-blk_write_time"
    },
    {
     "expr": "rate(pg_stat_database_blk_read_time{server=\"$instance\", datname=~\"$db\"}[5m])",
     "legendFormat": "{{datname}}-blk_read_time"
    }
   ]
  },
  { "title": "Others", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Lock Tables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_locks_count{server=\"$instance\", datname=~\"$db\"}",
     "legendFormat": "{{datname}}-{{mode}}"
    }
   ]
  },
  {
   "title": "blk_read_time/blk_read",
   "type": "timeseries",
   "description": "每个 blk 的读取时间",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blk_read_time{server=\"$instance\", datname=~\"$db\"}[5m]) / \nrate(pg_stat_database_blks_read{server=\"$instance\", datname=~\"$db\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_write_time{server=\"$instance\"}[5m])",
     "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
    },
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time{server=\"$instance\"}[5m])",
     "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
    }
   ]
  },
  {
   "title": "Checkpoint Counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pg_stat_bgwriter_checkpoints_timed{server=\"$instance\"}[1m])",
     "legendFormat": "checkpoints_timed - Number of scheduled checkpoints that have been performed"
    },
    {
     "expr": "increase(pg_stat_bgwriter_checkpoints_req{server=\"$instance\"}[1m])",
     "legendFormat": "checkpoints_req - Number of requested checkpoints that have been performed"
    }
   ]
  }
 ]
}