{
 "title": "Redis Cluster",
 "description": "Redis Dashboard for Prometheus Redis Exporter 1.x",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Zone", "query": "prometheus" },
   { "name": "job", "label": "Cluster", "query": { "query": "label_values(redis_up, job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(redis_up{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Node ",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum without (run_id) (redis_instance_info{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}-{{role}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "table",
   "description": "latency-monitor-threshold\n\nThe Redis latency monitoring subsystem samples different operations at runtime in order to collect data related to possible sources of latency of a Redis instance.When its value is set to zero, the latency monitor is turned off.The system only logs operations that were performed in a time equal or greater than the amount of milliseconds specified via the latency-monitor-threshold configuration directive",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis_latency_spike_last{job=~\"$job\", instance=~\"$instance\"} * 1000",
     "legendFormat": "{{instance}}-{{event_name}}"
    },
    {
     "expr": "redis_latency_spike_duration_seconds{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{event_name}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(redis_net_input_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Input"
    },
    {
     "expr": "sum(rate(redis_net_output_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Connected / Blocked Clients",
   "type": "timeseries",
   "description": "connected_clients: Number of client connections (excluding connections from replicas)\n\nblocked_clients: Number of clients pending on a blocking call (BLPOP, BRPOP, BRPOPLPUSH, BLMOVE, BZPOPMIN, BZPOPMAX)",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(redis_connected_clients{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "connected"
    },
    {
     "expr": "sum(redis_blocked_clients{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "blocked"
    }
   ]
  },
  {
   "title": "Total Commands / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{job=~\"$job\", instance=~\"$instance\"} [$__interval])) by (cmd)",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Hits & Misses / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(redis_keyspace_hits_total{job=~\"$job\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "hits, {{ instance }}"
    },
    {
     "expr": "rate(redis_keyspace_misses_total{job=~\"$job\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "misses, {{ instance }}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(redis_memory_used_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(redis_memory_max_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(redis_memory_used_rss_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "used_rss"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{job=~\"$job\", instance=~\"$instance\"}) by (db, instance)",
     "legendFormat": "{{ db }}, {{ instance }}"
    }
   ]
  },
  {
   "title": "Expired / Evicted Keys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{job=~\"$job\", instance=~\"$instance\"}[$__interval])) by (instance)",
     "legendFormat": "expired, {{ instance }}"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{job=~\"$job\", instance=~\"$instance\"}[$__interval])) by (instance)",
     "legendFormat": "evicted, {{ instance }}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{job=~\"$job\", instance=~\"$instance\"}) by (instance) - sum (redis_db_keys_expiring{job=~\"$job\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "not expiring, {{ instance }}"
    },
    {
     "expr": "sum (redis_db_keys_expiring{job=~\"$job\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "expiring, {{ instance }}"
    }
   ]
  },
  {
   "title": "Average Time Spent by Command / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(redis_commands_duration_seconds_total{job=~\"$job\", instance =~ \"$instance\"}[$__interval])) by (cmd)\n  /\nsum(rate(redis_commands_total{job=~\"$job\", instance =~ \"$instance\"}[$__interval])) by (cmd)\n",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Total Time Spent by Command / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_duration_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__interval])) by (cmd) > 0",
     "legendFormat": "{{ cmd }}"
    }
   ]
  }
 ]
}