version: '3'
services:

  nginx:
    build: 
      context: ./build
      dockerfile: Dockerfile
      args:
        NGINX_VERSION: 1.22
        XRAY_VERSION: v1.7.5
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/www/:/usr/share/nginx/html/
      - ./certbot/conf/:/etc/letsencrypt/
    environment:
      - CERTBOT_DOMAIN=cobolbaby.xyz
      - CERTBOT_EMAIL=cobolbaby@qq.com
    restart: always
