version: '3'
services:

  nginx:
    build: 
      context: ./build
      dockerfile: Dockerfile
      args:
        NGINX_VERSION: 1.20
        XRAY_VERSION: v1.17.5
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CERTBOT_DOMAIN=cobolbaby.xyz
      - CERTBOT_EMAIL=cobolbaby@qq.com
    restart: always
