version: '3.4'

x-patroni:
  &patroni_env
  PATRONI_ENABLE: 'true'
  PATRONI_NAMESPACE: pgcluster
  PATRONI_SCOPE: pgcluster_itc_12
  PATRONI_ETCD_HOSTS: "'etcd1:8917','etcd2:8917','etcd3:8917'"
  PATRONI_SUPERUSER_USERNAME: postgres
  PATRONI_SUPERUSER_PASSWORD: ******
  PATRONI_REPLICATION_USERNAME: replicator
  PATRONI_REPLICATION_PASSWORD: ******
  # PATRONI_RESTAPI_USERNAME: admin
  # PATRONI_RESTAPI_PASSWORD: admin
  # PATRONI_LOG_LEVEL: DEBUG
  PGDATA: /var/lib/postgresql/12/data
  # PG_RESTORE_STANZA: itc

x-default:
  &default_cfg
  extra_hosts:
    - 'etcd1:10.191.7.15'
    - 'etcd2:10.191.7.16'
    - 'etcd3:10.191.7.17'
  logging:
    driver: 'json-file'
    options:
      max-size: 10m

services:

  pg1201:
    << : *default_cfg
    image: registry.inventec/infra/postgres:12.14
    hostname: pg1201
    ports:
      - target: 5432
        published: 5493
        protocol: tcp
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/hdd/pg/12/data:/var/lib/postgresql/12/data
      - /data/ssd/pg/12/data:/data/postgresql/12/data
    environment:
      << : *patroni_env
      PATRONI_NAME: pg1201
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.alias == bdc06.infra.dev.itc.inventec
      resources:
        limits:
          cpus: "4"
          memory: 8g

  pg1202:
    << : *default_cfg
    image: registry.inventec/infra/postgres:12.14
    hostname: pg1202
    ports:
      - target: 5432
        published: 5493
        protocol: tcp
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/hdd/pg/12/data:/var/lib/postgresql/12/data
      - /data/ssd/pg/12/data:/data/postgresql/12/data
    environment:
      << : *patroni_env
      PATRONI_NAME: pg1202
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.alias == bdc07.infra.dev.itc.inventec
      resources:
        limits:
          cpus: "4"
          memory: 8g

  pg1203:
    << : *default_cfg
    image: registry.inventec/infra/postgres:12.14
    hostname: pg1203
    ports:
      - target: 5432
        published: 5493
        protocol: tcp
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/hdd/pg/12/data:/var/lib/postgresql/12/data
      - /data/ssd/pg/12/data:/data/postgresql/12/data
    environment:
      << : *patroni_env
      PATRONI_NAME: pg1203
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.alias == bdc08.infra.dev.itc.inventec
      resources:
        limits:
          cpus: "4"
          memory: 8g

networks:
  default:
    external:
      name: bdc
